<?php

declare(strict_types=1);

namespace App\Service;

use App\Core\Database;
use App\Support\Phase5Budgets;

/**
 * Foundation F9 — renders the measured-vs-D11 budget report (entry-gate item
 * A3). Non-PENDING at Foundation: `resolver.p95` (a legacy BASELINE from
 * BaselineMetricsService — the number the future resolver must beat) and
 * `webhook.delivery_timeout` (a CONFIG cap). Every other D11 budget lists its
 * target and stays PENDING until its increment measures it on this same fixture.
 * Read-only; writes only the evidence file the caller names.
 */
final class Phase5BudgetReportService
{
    public function __construct(private Database $db)
    {
    }

    /** @return array<int,array{key:string,metric:string,target:string,measured:string,status:string}> */
    public function rows(): array
    {
        $baseline = (new BaselineMetricsService($this->db))->measureLegacyAuthorityRead();
        $rows = [];
        foreach (Phase5Budgets::all() as $key => $b) {
            $target = $b['target'] . ' ' . $b['unit'] . ' (' . $b['statistic'] . ')';
            $measured = '—';
            $status = 'PENDING (' . $b['measurable_at'] . ')';

            if ($key === 'resolver.p95') {
                $measured = $baseline['p95'] . ' ms legacy';
                $status = 'BASELINE';
            } elseif ($key === 'webhook.delivery_timeout') {
                $measured = '5000 ms configured';
                $status = 'CONFIG';
            }

            $rows[] = ['key' => $key, 'metric' => $b['metric'], 'target' => $target, 'measured' => $measured, 'status' => $status];
        }
        return $rows;
    }

    public function render(): string
    {
        $env = (new BaselineMetricsService($this->db))->measureLegacyAuthorityRead();
        $out = "# Phase 5 — Performance Budgets (A3, Foundation F9)\n\n";
        $out .= "> Generated by `bin/console verify:phase5-budgets`. Foundation measures the\n";
        $out .= "> resolver baseline (legacy authority read) + config caps; each later increment\n";
        $out .= "> fills its PENDING row on this same `Phase5FixtureSeeder` corpus.\n\n";
        $out .= "## Measurement envelope (PHASE_5_PLAN §11.3)\n\n";
        $out .= '- Route/job: `' . $env['route_or_job'] . "`\n";
        $out .= '- PHP: ' . $env['php_version'] . ' · DB: ' . $env['db_version'] . "\n";
        $out .= '- Hardware class: ' . $env['hardware_class'] . ' · OS/isolation: ' . $env['os_isolation_profile'] . "\n";
        $out .= '- Fixture: ' . $env['data_fixture'] . ' · role assignments: ' . $env['role_assignment_count'] . "\n";
        $out .= '- Window: ' . $env['window'] . ' · concurrency: ' . $env['concurrency'] . ' · cache: ' . $env['cache_state'] . "\n";
        $out .= '- Legacy read p50/p95/p99 (ms): ' . $env['p50'] . ' / ' . $env['p95'] . ' / ' . $env['p99'] . "\n";
        $out .= '- Queries: ' . $env['query_count'] . ' · query time (ms): ' . $env['query_time_ms']
             . ' · peak mem (bytes): ' . $env['peak_memory_bytes'] . ' · error rate: ' . $env['error_rate'] . "\n\n";
        $out .= "## Budgets vs D11 targets (ADR 0004 D11)\n\n";
        $out .= "| Budget | Metric | Target | Measured | Status |\n";
        $out .= "|---|---|---|---|---|\n";
        foreach ($this->rows() as $r) {
            $out .= '| `' . $r['key'] . '` | ' . $r['metric'] . ' | ' . $r['target'] . ' | ' . $r['measured'] . ' | ' . $r['status'] . " |\n";
        }
        return $out;
    }

    public function write(string $path): int
    {
        $bytes = file_put_contents($path, $this->render());
        if ($bytes === false) {
            throw new \RuntimeException("could not write budget report to $path");
        }
        return $bytes;
    }
}
