# fly.toml app configuration file generated for community-forums on 2026-08-06T04:39:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'community-forums'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'php bin/console migrate'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_URL = 'https://community-forums.fly.dev'
  PACKAGES_STORAGE_PATH = '/data/packages'
  RATELIMIT_PATH = '/data/ratelimit'
  SECURITY_HSTS = 'true'
  SESSION_SECURE = 'true'
  UPLOADS_PATH = '/data/media'

[[mounts]]
  source = 'community_forums_data'
  destination = '/data'
  initial_size = '3gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
